### ISSUE TITLE
Latest simplewebrtc not supported

### ISSUE THREAD

**Issue by Aksi0m** [bahmutov/ng-simple-webrtc#17]
Broadcasting does not work with the simplewebrtc 2.1.1 version. No errors in console, it just does not work. Maybe we can figure it out together...

**Comment by samsont** [comment]
Try our  Sept 3, 2015 build, 0.20.0.

**Comment by Aksi0m** [comment]
It works with this version. Thanks! If you guys need any help, let me know. I will work with your lib on a project for the next 1,5 months. Great work btw!
