### ISSUE TITLE
Pubnub as the signaling server

### ISSUE THREAD

**Issue by Welborn09** [bahmutov/ng-simple-webrtc#23]
I was playing with this code, nice job btw. Can you give some pointers on how to implement PubNub into this? I am thinking that pubnub would be a wrapper around your webrtc methods. if this is the case, would it be I would call pubnub.join (for example) and it would in turn call your webrtc.join?

**Comment by bahmutov** [comment]
hmm, not sure how to do this, but hopefully you can come up with a way

**Comment by Welborn09** [comment]
well..thats not very good direction there. But ok, let me see what I can do.
